---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: ping_db
  pull: default
  image: postgres:11.2-alpine
  commands:
  - "until PGPASSWORD=postgres psql -U postgres -d infomark -h database \\\n -c \"SELECT 1;\" >/dev/null 2>&1; do sleep 1; done\n"
  - "PGPASSWORD=postgres psql -U postgres -d infomark -h database \\\n  -c \"SELECT * FROM pg_catalog.pg_tables;\"\n"

- name: ping_amqp
  pull: default
  image: rabbitmq:3.7.3-management-alpine
  commands:
  - "until wget --spider http://rabbitAMQP:15672 >/dev/null 2>&1; do sleep 1; done"

- name: ping_redis
  pull: default
  image: redis:5.0.4-alpine
  commands:
  - "until redis-cli -h redis_service ping >/dev/null 2>&1; do sleep 1; done"
  - redis-cli -h redis_service  FLUSHALL

- name: mock
  pull: default
  image: python:3
  commands:
  - cd database
  - pip3 install -r requirements.txt
  - python3 mock.py

- name: seed
  pull: default
  image: postgres:11.2-alpine
  commands:
  - cd database
  - "PGPASSWORD=postgres psql -h 'database' -U 'postgres' -d 'infomark' -f schema.sql >/dev/null"
  - "PGPASSWORD=postgres psql -h 'database' -U 'postgres' -d 'infomark' -f migrations/0.0.1alpha14.sql >/dev/null"
  - "PGPASSWORD=postgres psql -h 'database' -U 'postgres' -d 'infomark' -f migrations/0.0.1alpha21.sql >/dev/null"
  - "PGPASSWORD=postgres psql -h 'database' -U 'postgres' -d 'infomark' -f mock.sql >/dev/null"

- name: build
  pull: default
  image: golang
  commands:
  - sed -i 's/"X-INFOMARK-VERSION", "0.0.1"/"X-INFOMARK-VERSION", "${DRONE_COMMIT_SHA}"/g' api/app/router.go
  - go version
  - go build infomark.go
  environment:
    GOPROXY: https://gomods.patwie.com/

- name: test
  pull: default
  image: golang
  commands:
  - cp .infomark.yml.ci .infomark.yml
  - export INFOMARK_CONFIG_DIR=`pwd`
  -
  - go test ./api/app -cover -v --goblin.timeout 15s
  - go test ./api/helper -cover -v
  environment:
    GOPROXY: https://gomods.patwie.com/

- name: docs
  pull: default
  image: golang
  commands:
  - go generate
  environment:
    GOPROXY: https://gomods.patwie.com/

- name: create_release
  pull: default
  image: patwie/tar
  commands:
    - tar -czvf infomark-backend.tar.gz api.yaml infomark README.md LICENSE .infomark.example.yml docker-compose.example.yml database/schema.sql email/*.txt files/uploads/ files/generated_files/ files/common/ database/migrations

- name: publish_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - infomark-backend.tar.gz
    checksum:
      - md5
      - sha256
  when:
    event: tag

services:
- name: database
  pull: default
  image: postgres:11.2-alpine
  environment:
    POSTGRES_DB: infomark
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres

- name: rabbitAMQP
  pull: default
  image: rabbitmq:3.7.3-management-alpine
  environment:
    RABBITMQ_DEFAULT_PASS: password
    RABBITMQ_DEFAULT_USER: user

- name: redis_service
  pull: default
  image: redis:5.0.4-alpine

---
kind: signature
hmac: 96c71a82796008f906b69d1e50a485b8efc22262fa0a0d6dad330d9d5b6f0575

...
