server:
  version: 1
  debugging:
    enabled: false
    user_id: 1
    user_is_root: false
    log_level: debug
    fixtures: /drone/src/files/fixtures
  http:
    use_https: false
    port: 3000
    domain: sub.domain.com
    timeouts:
      read: 30s
      write: 30s
    limits:
      max_header: 1mb
      max_request_json: 2mb
      max_submission: 4mb
  distribute_jobs: true
  authentication:
    jwt:
      secret: 4b86a7b05ddf6c8f27ca57078b02c086e5ecdb7737c019c8286c7f71e86e4fbe
      access_expiry: 15m0s
      refresh_expiry: 10h0m0s
    session:
      secret: d28a1b649f96340c6831d198e78ea08894c30aaa32fccc02e35c1ac32eff908a
      cookies:
        secure: false
        lifetime: 24h0m0s
        idle_timeout: 1h0m0s
    password:
      min_length: 7
    total_requests_per_minute: 10
  cronjobs:
    zip_submissions_intervall: 5m0s
  email:
    send: true
    sendmail_binary: /usr/sbin/sendmail
    from: no-reply@sub.domain.com
    channel_size: 300
  services:
    redis:
      host: redis_service
      port: 6379
      database: 0
    rabbit_mq:
      host: localhost
      port: 5672
      user: user
      password: password
      key: rabbitmq_key
    database:
      host: database
      port: 5432
      database: infomark
      user: postgres
      password: postgres
      debug: false
  paths:
    uploads: /drone/src/files/uploads
    common: /drone/src/files/common
    generated_files: /drone/src/files/generated_files
worker:
  version: 1
  services:
    rabbit_mq:
      host: localhost
      port: 5672
      user: rabbitmq_user
      password: password
      key: rabbitmq_key
  workdir: /tmp
  void: false
  docker:
    max_memory: 500mb
    timeout: 5m0s

