version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.7.3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/data
  database:
    image: postgres:11.2-alpine
    environment:
      # openssl rand -hex 32
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - PGPASSWORD=pass
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  rabbitmq_data:
  db-data:
